### ISSUE TITLE
Add support for new FontAwesome 6 syntax

### ISSUE THREAD

**Issue by stefanobartoletti** [FA-Minify/fa-minify#4]
FontAwesome 6 introduced a new syntax to include icons in HTML templates. Examples of the new classes [from the official docs](https://fontawesome.com/docs/web/setup/upgrade/whats-changed#full-style-names):

- `fas` becomes `fa-solid`
- `far` becomes `fa-regular`
- `fab` becomes `fa-brands`

and so on.

The old classes (`fas`, `fab`, etc.) are still valid, but I think that it would be nice to have `fa-minify` also support the new classes as well.

**Comment by NetWin** [comment]
Good point, I'll look into that. 👍🏼

Did you try `fa-minify` with FA6 out already? Not sure if it works at all tbh.

**Comment by NetWin** [comment]
I checked it out and added support for FA6.

The config of `fa-minify` will still only work with `far/fas/fab/...` instead of `fa-regular/fa-solid/fa-brands/...`. 
But it does export files including definitions for the long classname of icons. (As long as you give it a `FontAwesome@^6` all.js file obviously)

I updated https://fa-minify.com and the gulp-plugin to support FA6 and did some householding while working on it.

With `fa-minify@^6` and `FontAwesome@^6` you can use long icon classes within you html like:
```html
<html>

  <head>
    <script src="all.fa-minified.js"></script>
  </head>

  <body>

    <!-- long form -->
    <i class="fa-regular fa-address-book"></i>

    <!-- short form -->
    <i class="far fa-address-book"></i>

  </body>

</html>
```

Result: 
![image](https://user-images.githubusercontent.com/7582077/153740200-044b67e6-428f-476f-baa5-47070d45f8b6.png)

**Comment by stefanobartoletti** [comment]
Thank you, I just tested the new version and it works wonderfully!
